### ISSUE TITLE
Can't fetch achievements

### ISSUE THREAD

**Issue by Moa-Kikuchi** [PaulCombal/SamRewritten#132]
Arch Linux. RebornOS.

Error Log.

Steam_SetMinidumpSteamID:  Caching Steam ID:  76561198041911058 [API loaded no]
Received stats for the game, but an error occurrred.
GlobalStatsReceived_t failed! Enum: 11
GlobalAchievementPercentagesReady_t failed! Enum: 11
Write pipe encountered fatal error.
^CRead pipe encountered fatal error.
Read pipe encountered fatal error.

**Comment by Moa-Kikuchi** [comment]
installing the game before managing achievements fixed this issue. I was being silly. thank you for your work!

**Comment by PaulCombal** [comment]
Weird.. is it the same for all games? You shouldn't have to install the game to fetch the achievements

**Comment by Moa-Kikuchi** [comment]
I tried 5 different uninstalled games and all of them provided the same
result. It would attempt to fetch achievements before freezing then
crashing.

Samrewritten was installed from Aur and Steam was installed using pacman if
that makes any difference. Let me know if there's any more info I
can provide!

Thanks.
